# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
---

# Always use 3 digits for the version number
name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
version-template: $MAJOR.$MINOR.$PATCH

categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: ⚠️ Deprecated
    labels:
      - deprecated
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
      - regression-fix
  - title: 📝 Documentation updates
    labels:
      - documentation
  - title: 👻 Maintenance
    labels:
      - chore
      - internal
      - maintenance
  - title: 🚦 Tests
    labels:
      - test
      - tests
  - title: ✍ Other changes
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    labels:
      - dependencies
    collapse-after: 15
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

template: |
  <!-- Optional: add a release summary here -->
  $CHANGES
