repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.38.0
  hooks:
    - id: check-renovate
      name: Check renovate schema
exclude: ^src/test/resources/oci/
