name: updatecli
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 2am UTC
  push:
  pull_request:
permissions:
  contents: read

jobs:
  updatecli:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository_owner == 'oras-project'
    steps:

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@e71be7554f3f940bc439cf720b3e4e379823c562 # v3.2.0

      - name: Run Updatecli in Dry Run mode
        run: updatecli diff --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Updatecli in Apply mode
        if: github.ref == 'refs/heads/main'
        run: updatecli apply --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
